require("skynet.manager")
local skynet  	= require("skynet")
require("proto_map")
skynet.start(function()
    skynet.newservice("debug_console")
    local datacenterd = skynet.newservice("datacenterd")
    skynet.name(SERVICE.DATACENTER, datacenterd)
    skynet.newservice("main_db")
    print("db server start")
    skynet.exit()
end)
