local skynet  	= require("skynet")
local logger  	= require("log")
local clientHelper = require("common.client_helper")
--local configCheck = require("config_check.config_check_ctrl")

clientHelper.registerProtos()
skynet.start(function()
    skynet.newservice("debug_console")
    skynet.newservice("auth")
    skynet.newservice("watchdog")
    --skynet.newservice("record")
    skynet.newservice("push")
    print("frontend server start")
    skynet.exit()
end)
