local skynet  	= require("skynet")
local clientHelper = require("common.client_helper")
clientHelper.registerProtos()

skynet.start(function()
	skynet.newservice("debug_console")
	skynet.newservice("simple_http")
	skynet.newservice("marquee")
	skynet.newservice("record")
	skynet.newservice("charge")
	skynet.newservice("red_money")
	skynet.newservice("statistic")
	skynet.newservice("rank")
	skynet.newservice("mail_svc")
	skynet.newservice("pot")
	skynet.newservice("perfor_monitor")
	skynet.exit()
end)