--[[
	序号, 类型, 数量, 描述, 内容, 图标, 奖励类型, 奖励
	id, type, num, desc, content, icon, awardType, award
]]
local coupon_award = {
	[1] = {
			id = 1,
			type = 1,
			num = 1,
			desc = [[收集1个<img path='res/icon/icon_1.png' restype=0 scale=0.5 />]],
			content = [[8000金币]],
			icon = [[gold_1]],
			awardType = 1,
			award = {goodsId=1,amount=8000},
		},
	[2] = {
			id = 2,
			type = 2,
			num = 1,
			desc = [[收集1个<img path='res/icon/icon_2.png' restype=0 scale=0.5 />]],
			content = [[20000金币]],
			icon = [[gold_1]],
			awardType = 1,
			award = {goodsId=1,amount=20000},
		},
	[3] = {
			id = 3,
			type = 3,
			num = 1,
			desc = [[收集1个<img path='res/icon/icon_3.png' restype=0 scale=0.5 />]],
			content = [[60000金币]],
			icon = [[gold_1]],
			awardType = 1,
			award = {goodsId=1,amount=60000},
		},
	[4] = {
			id = 4,
			type = 4,
			num = 1,
			desc = [[收集1个<img path='res/icon/icon_4.png' restype=0 scale=0.5 />]],
			content = [[100000金币]],
			icon = [[gold_1]],
			awardType = 1,
			award = {goodsId=1,amount=100000},
		},
	[5] = {
			id = 5,
			type = 1,
			num = 2,
			desc = [[收集2个<img path='res/icon/icon_1.png' restype=0 scale=0.5 />]],
			content = [[16000金币]],
			icon = [[gold_1]],
			awardType = 1,
			award = {goodsId=1,amount=16000},
		},
	[6] = {
			id = 6,
			type = 2,
			num = 2,
			desc = [[收集2个<img path='res/icon/icon_2.png' restype=0 scale=0.5 />]],
			content = [[40000金币]],
			icon = [[gold_1]],
			awardType = 1,
			award = {goodsId=1,amount=40000},
		},
	[7] = {
			id = 7,
			type = 3,
			num = 2,
			desc = [[收集2个<img path='res/icon/icon_3.png' restype=0 scale=0.5 />]],
			content = [[120000金币]],
			icon = [[gold_2]],
			awardType = 1,
			award = {goodsId=1,amount=120000},
		},
	[8] = {
			id = 8,
			type = 4,
			num = 2,
			desc = [[收集2个<img path='res/icon/icon_4.png' restype=0 scale=0.5 />]],
			content = [[200000金币]],
			icon = [[gold_2]],
			awardType = 1,
			award = {goodsId=1,amount=200000},
		},
	[9] = {
			id = 9,
			type = 1,
			num = 3,
			desc = [[收集3个<img path='res/icon/icon_1.png' restype=0 scale=0.5 />]],
			content = [[32000金币]],
			icon = [[gold_2]],
			awardType = 1,
			award = {goodsId=1,amount=32000},
		},
	[10] = {
			id = 10,
			type = 2,
			num = 3,
			desc = [[收集3个<img path='res/icon/icon_2.png' restype=0 scale=0.5 />]],
			content = [[80000金币]],
			icon = [[gold_2]],
			awardType = 1,
			award = {goodsId=1,amount=80000},
		},
	[11] = {
			id = 11,
			type = 3,
			num = 3,
			desc = [[收集3个<img path='res/icon/icon_3.png' restype=0 scale=0.5 />]],
			content = [[240000金币]],
			icon = [[gold_2]],
			awardType = 1,
			award = {goodsId=1,amount=240000},
		},
	[12] = {
			id = 12,
			type = 4,
			num = 3,
			desc = [[收集3个<img path='res/icon/icon_4.png' restype=0 scale=0.5 />]],
			content = [[双生之力]],
			icon = [[gun_10]],
			awardType = 2,
			award = {gunId=8},
		},
}
return coupon_award