--[[
	序号, 下一步对话, 描述, 控件名字, 箭头方向, 光圈, 对话框偏移, 其他参数
	id, nextId, content, widgetName, arrow, sign, offset, params
]]
local guide_config = {
	[1] = {
			id = 1,
			nextId = 3,
			content = [[恭喜获得1张<font color=#da7b00,1 >夺宝卡！！！</font>]],
			widgetName = {"CATCH_FISH_UI","pnlCard"},
			arrow = {dir = 2,offset = {70,100},scale = 1},
			sign = {scale = 1,offset = {70,5}},
			offset = {0,-100},
			params = {selfPos=true,isGirlFlip=true,isBgFlip=true,girlOffset={-150,20},textOffset={-60,70}},
		},
	[2] = {
			id = 2,
			nextId = 3,
			content = [[一起和小伙伴参与<font color=#da7b00,1 >夺宝活动</font>赢取大奖吧！]],
			widgetName = {"CATCH_FISH_UI","btnMenu"},
			arrow = {dir = 4,offset = {-130,-20},scale = 1},
			sign = {scale = 1,offset = {0,0}},
			offset = {0,0},
			params = {selfPos=true,isGirlFlip=true,isBgFlip=true,girlOffset={-150,20},textOffset={-60,70},doNextLimit = true,canSkip = true},
		},
	[3] = {
			id = 3,
			nextId = 4,
			content = [[先来看看有哪些奖品！]],
			widgetName = {"CATCH_FISH_UI","btnFund"},
			arrow = {dir = 1,offset = {0,-130},scale = 1},
			sign = {scale = 1,offset = {0,0}},
			offset = {60,20},
			params = {selfPos=true,isGirlFlip=true,isBgFlip=true,girlOffset={-150,20},textOffset={-60,70}},
		},
	[4] = {
			id = 4,
			nextId = 5,
			content = [[现在来尝试第一次夺宝吧！]],
			widgetName = {"FUND_VIEW","pnlShopItem1"},
			arrow = {dir = 1,offset = {130,0},scale = 1},
			sign = {scale = 1,offset = {130,150}},
			offset = {0,0},
			params = {},
		},
	[5] = {
			id = 5,
			nextId = 6,
			content = [[1张<font color=#da7b00,1 >夺宝卡</font>可参与1人次，参与人次越多中奖的几率越高哦！]],
			widgetName = {"FUND_VIEW","btnBuy"},
			arrow = {dir = 2,offset = {0,80},scale = 1},
			sign = {scale = 1,offset = {0,0}},
			offset = {0,-100},
			params = {selfPos=true,isGirlFlip=true,isBgFlip=true,girlOffset={-150,20},textOffset={-60,70}},
		},
	[6] = {
			id = 6,
			nextId = 0,
			content = [[通过夺宝记录可查看参与记录和中奖结果。]],
			widgetName = {"FUND_VIEW","guide_fund_records"},
			arrow = {dir = 2,offset = {0,-150},scale = -1},
			sign = {scale = 1,offset = {0,0}},
			offset = {0,-100},
			params = {selfPos=true,isGirlFlip=true,isBgFlip=true,girlOffset={-150,20},textOffset={-60,70}},
		},
	[101] = {
			id = 101,
			nextId = 102,
			content = [[<font color=#da7b00,1 >夺宝卡</font>可以用来参加夺宝！]],
			widgetName = {"CATCH_FISH_UI","pnlCard"},
			arrow = {dir = 2,offset = {70,80},scale = 1},
			sign = {scale = 1,offset = {70,5}},
			offset = {80,-100},
			params = {selfPos=true,isGirlFlip=true,isBgFlip=true,girlOffset={-150,20},textOffset={-60,70}},
		},
	[102] = {
			id = 102,
			nextId = 103,
			content = [[参加夺宝前必须先<font color=#da7b00,1 >绑定手机号码</font>！]],
			widgetName = {"CATCH_FISH_UI","btnMenu"},
			arrow = {dir = 4,offset = {-140,0},scale = 1},
			sign = {scale = 1,offset = {0,4}},
			offset = {130,30},
			params = {selfPos=true,isGirlFlip=true,isBgFlip=true,girlOffset={-150,20},textOffset={-60,70},doNextLimit = true,canSkip = true},
		},
	[103] = {
			id = 103,
			nextId = 104,
			content = [[设置界面可以<font color=#da7b00,1 >绑定手机号码</font>！]],
			widgetName = {"CATCH_FISH_UI","btnSetting"},
			arrow = {dir = 4,offset = {-130,0},scale = 1},
			sign = {scale = 1,offset = {0,0}},
			offset = {200,-70},
			params = {},
		},
	[104] = {
			id = 104,
			nextId = 0,
			content = [[现在去<font color=#da7b00,1 >绑定手机号码</font>吧！]],
			widgetName = {"SETTING_VIEW","tabItem4"},
			arrow = {dir = 3,offset = {150,0},scale = 1},
			sign = {scale = 1,offset = {75,-5}},
			offset = {0,-130},
			params = {},
		},
	[1001] = {
			id = 1001,
			nextId = 1002,
			content = [[恭喜你中奖了，请先填写收货信息！]],
			widgetName = {"CATCH_FISH_UI","btnMenu"},
			arrow = {dir = 4,offset = {-130,0},scale = 1},
			sign = {scale = 1,offset = {0,0}},
			offset = {0,0},
			params = {doNextLimit = true,canSkip = true},
		},
	[1002] = {
			id = 1002,
			nextId = 1003,
			content = [[现在马上去填写收货信息！]],
			widgetName = {"CATCH_FISH_UI","btnFund"},
			arrow = {dir = 1,offset = {0,-100},scale = 1},
			sign = {scale = 1,offset = {0,0}},
			offset = {100,0},
			params = {},
		},
	[1003] = {
			id = 1003,
			nextId = 0,
			content = [[收货信息很重要，请认真填写哦！]],
			widgetName = {"FUND_VIEW","tabItem4"},
			arrow = {dir = 3,offset = {80,0},scale = 1},
			sign = {scale = 1,offset = {0,0}},
			offset = {100,0},
			params = {},
		},
	[10001] = {
			id = 10001,
			nextId = 10002,
			content = [[恭喜您获得了新炮台，点击当前炮台可更换新炮台]],
			widgetName = {"CATCH_FISH_UI","gun_img"},
			arrow = {dir = 2,offset = {0,160},scale = 1},
			sign = {scale = 1,offset = {0,55}},
			offset = {-30,-110},
			params = {selfPos = true, isGirlFlip = true, isBgFlip = true, girlOffset = {-150,0}, textOffset = {-60,70}},
		},
	[10002] = {
			id = 10002,
			nextId = 0,
			content = [[请点击换炮]],
			widgetName = {"CATCH_FISH_UI","change_gun"},
			arrow = {dir = 2,offset = {0,80},scale = 1},
			sign = {scale = 1,offset = {0,0}},
			offset = {-100,-100},
			params = {selfPos = true, isGirlFlip = true, isBgFlip = true, girlOffset = {-150,0}, textOffset = {-60,70}},
		},
}
return guide_config