--[[
	类型, 名称, 消耗, 最小炮倍, 最大炮倍, 发炮间隔, 捕获率加成, 技能
	type, name, cost, minLevel, maxLevel, fireInterval, cp, skill
]]
local gun = {
	[1] = {
			type = 1,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[2] = {
			type = 2,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[3] = {
			type = 3,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[4] = {
			type = 4,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[5] = {
			type = 5,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 150,
			cp = 0,
			skill = {},
		},
	[6] = {
			type = 6,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[7] = {
			type = 7,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = -150,
			skill = {},
		},
	[8] = {
			type = 8,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[9] = {
			type = 9,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {name = "frozen"},
		},
	[10] = {
			type = 10,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[11] = {
			type = 11,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {name = "violent"},
		},
	[12] = {
			type = 12,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[13] = {
			type = 13,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {},
		},
	[15] = {
			type = 15,
			cost = 1,
			minLevel = 10,
			maxLevel = 1000,
			fireInterval = 200,
			cp = 0,
			skill = {name = "slice"},
		},
}
return gun