--[[
	ID, , 名称, 图标, 图标文字, appstore时是否隐藏, 游戏中是否显示, 显示规则, 所属组, 大厅所属组, 附加参数
	id, , name, icon, text, isHideByAppstore, isHideByGame, displayRule, group, hallGroup, params
]]
local icon_config = {
 {
		id = 3,
		name = [[Box]],
		icon = [[box]],
		text = [[box_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 1,
		hallGroup = 0,
		params = {effects = {"flash"}},
	},
 {
		id = 4,
		name = [[Fruit]],
		icon = [[fruit]],
		text = [[fruit_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 1,
		group = 1,
		hallGroup = 0,
		params = {effects = {"flash"}},
	},
 {
		id = 5,
		name = [[First]],
		icon = [[first]],
		text = [[first_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 1,
		group = 3,
		hallGroup = 0,
		params = {effects = {"glow","star"}},
	},
 {
		id = 7,
		name = [[Share]],
		icon = [[share]],
		text = [[share_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 3,
		hallGroup = 0,
		params = {},
	},
 {
		id = 8,
		name = [[Mail]],
		icon = [[mail]],
		text = [[mail_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 1,
		group = 3,
		hallGroup = 0,
		params = {effects = {"redPoint"}},
	},
 {
		id = 9,
		name = [[SuperVip]],
		icon = [[super_vip]],
		text = [[super_vip_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 3,
		hallGroup = 0,
		params = {},
	},
 {
		id = 10,
		name = [[Regular]],
		icon = [[regular]],
		text = [[regular_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 2,
		hallGroup = 0,
		params = {},
	},
 {
		id = 11,
		name = [[Setting]],
		icon = [[setting]],
		text = [[setting_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 2,
		hallGroup = 0,
		params = {},
	},
 {
		id = 12,
		name = [[Help]],
		icon = [[help]],
		text = [[help_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 2,
		hallGroup = 0,
		params = {},
	},
 {
		id = 13,
		name = [[Customer]],
		icon = [[customer]],
		text = [[customer_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 2,
		hallGroup = 0,
		params = {noBg = true},
	},
 {
		id = 14,
		name = [[Change]],
		icon = [[change]],
		text = [[change_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 2,
		hallGroup = 0,
		params = {},
	},
 {
		id = 6,
		name = [[Hide]],
		icon = [[less_icon]],
		text = [[less_icon_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 4,
		hallGroup = 0,
		params = {effects = {"redPoint"}},
	},
 {
		id = 41,
		name = [[Online]],
		icon = [[online]],
		text = [[online_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 7,
		hallGroup = 0,
		params = {effects = {"star","redPoint"},leftTime = true},
	},
 {
		id = 37,
		name = [[Recharge]],
		icon = [[recharge]],
		text = [[recharge_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 0,
		group = 4,
		hallGroup = 0,
		params = {effects = {"glow","star"},tip = {flip = {-1,1},content = "点击充值金币",offset = {65,30}}},
	},
 {
		id = 17,
		name = [[Aim]],
		icon = [[aim]],
		text = [[aim_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 5,
		hallGroup = 0,
		params = {noBg = true,effects = {"aim"}},
	},
 {
		id = 38,
		name = [[Prize]],
		icon = [[prize]],
		text = [[prize_txt]],
		isHideByAppstore = 1,
		isHideByGame = 0,
		displayRule = 1,
		group = 5,
		hallGroup = 0,
		params = {effects = {"flash"}},
	},
 {
		id = 18,
		name = [[Auto]],
		icon = [[auto]],
		text = [[auto_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 5,
		hallGroup = 0,
		params = {noBg = true,effects = {"aim"}},
	},
 {
		id = 1,
		name = [[Exchange]],
		icon = [[exchange]],
		text = [[exchange_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 0,
		group = 6,
		hallGroup = 0,
		params = {effects = {"btn_light"},tip = {flip = {-1,1},content = "点此进入商城兑换奖品",offset = {15,0}}},
	},
 {
		id = 2,
		name = [[Fund]],
		icon = [[fund]],
		text = [[fund_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 0,
		group = 6,
		hallGroup = 0,
		params = {effects = {"btn_light","readPoint"},tip = {flip = {1,1},content = "点此参加渔场夺宝活动",offset = {-10,0}}},
	},
 {
		id = 19,
		name = [[Vip]],
		icon = [[vip]],
		text = [[vip_txt]],
		isHideByAppstore = 1,
		isHideByGame = 0,
		displayRule = 1,
		group = 6,
		hallGroup = 0,
		params = {effects = {"star"},tip = {flip = {1,1},content = "点击进入VIP专人房间",offset = {-30,0}}},
	},
 {
		id = 20,
		name = [[Arena]],
		icon = [[arena]],
		text = [[arena_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 1,
		group = 6,
		hallGroup = 0,
		params = {effects = {"star","redPoint"},tip = {flip = {1,1},content = "点击参加比赛赢奖金",offset = {-50,0}}},
	},
 {
		id = 21,
		name = [[Activity]],
		icon = [[activity]],
		text = [[activity_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 0,
		group = 7,
		hallGroup = 0,
		params = {effects = {"jell","star","redPoint"}},
	},
 {
		id = 22,
		name = [[Chongzhi]],
		icon = [[chongzhi]],
		text = [[chongzhi_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 7,
		hallGroup = 0,
		params = {effects = {"jell","star","redPoint"}},
	},
 {
		id = 23,
		name = [[Coupon]],
		icon = [[coupon]],
		text = [[coupon_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 7,
		hallGroup = 0,
		params = {effects = {"jell","star","redPoint"}},
	},
 {
		id = 24,
		name = [[Treasure]],
		icon = [[treasure]],
		text = [[treasure_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 1,
		group = 7,
		hallGroup = 0,
		params = {effects = {"jell","star","redPoint"}},
	},
 {
		id = 25,
		name = [[Crazy]],
		icon = [[crazy]],
		text = [[crazy_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 0,
		group = 7,
		hallGroup = 0,
		params = {effects = {"jell","star","redPoint"}},
	},
 {
		id = 27,
		name = [[Seven]],
		icon = [[seven]],
		text = [[seven_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 1,
		group = 7,
		hallGroup = 0,
		params = {effects = {"jell","star","redPoint"}},
	},
 {
		id = 29,
		name = [[Replace]],
		icon = [[replace]],
		text = [[replace_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 7,
		hallGroup = 0,
		params = {effects = {"star","arrow"}},
	},
 {
		id = 30,
		name = [[Lottery]],
		icon = [[lottery]],
		text = [[lottery_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 8,
		hallGroup = 0,
		params = {effects = {"star"}},
	},
 {
		id = 31,
		name = [[Bag]],
		icon = [[bag]],
		text = [[bag_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 1,
		group = 8,
		hallGroup = 0,
		params = {effects = {"flash","redPoint"}},
	},
 {
		id = 32,
		name = [[Wishwell]],
		icon = [[wishwell]],
		text = [[wishwell_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 1,
		group = 8,
		hallGroup = 0,
		params = {effects = {"flash"}},
	},
 {
		id = 33,
		name = [[Hunt]],
		icon = [[hunt]],
		text = [[hunt_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 8,
		hallGroup = 0,
		params = {effects = {"flash"}},
	},
 {
		id = 34,
		name = [[Bless]],
		icon = [[bless]],
		text = [[bless_txt]],
		isHideByAppstore = 0,
		isHideByGame = 1,
		displayRule = 0,
		group = 8,
		hallGroup = 0,
		params = {effects = {"flash"}},
	},
 {
		id = 35,
		name = [[Invite]],
		icon = [[invite_friend]],
		text = [[invite_friend_txt]],
		isHideByAppstore = 1,
		isHideByGame = 0,
		displayRule = 1,
		group = 8,
		hallGroup = 0,
		params = {effects = {"flash","redPoint"}},
	},
 {
		id = 16,
		name = [[WeekGift]],
		icon = [[week_gift]],
		text = [[week_gift_txt]],
		isHideByAppstore = 1,
		isHideByGame = 0,
		displayRule = 0,
		group = 8,
		hallGroup = 0,
		params = {effects = {"flash","redPoint"}},
	},
 {
		id = 39,
		name = [[Fund_1]],
		icon = [[fund]],
		text = [[fund_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 0,
		group = 1,
		hallGroup = 0,
		params = {effects = {"flash","redPoint"}},
	},
 {
		id = 40,
		name = [[Exchange_1]],
		icon = [[exchange]],
		text = [[exchange_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 0,
		group = 1,
		hallGroup = 0,
		params = {effects = {"flash"}},
	},
 {
		id = 42,
		name = [[SecondReward]],
		icon = [[exchange]],
		text = [[exchange_txt]],
		isHideByAppstore = 0,
		isHideByGame = 0,
		displayRule = 2,
		group = 7,
		hallGroup = 0,
		params = {effects = {"flash"}},
	},
}
return icon_config