--[[
	ID, 天, 登录奖励名称, 登录奖励图标, 登录奖励, 需要在线时间（秒）, 充值金额, 充值奖励名称, 充值奖励图标, 充值奖励
	id, day, loginAwardName, loginAwardIcon, loginAward, , recharge, rechargeAwardName, rechargeAwardIcon, rechargeAward
]]
local login_award_config = {
 {
		id = 1,
		day = [[第一天]],
		loginAwardName = [[500金币]],
		loginAwardIcon = [[gold_1]],
		loginAward = {goodsId=1,amount=500},
		recharge = 10,
		rechargeAwardName = [[2000金币]],
		rechargeAwardIcon = [[gold_2]],
		rechargeAward = {goodsId=1,amount=2000},
	},
 {
		id = 2,
		day = [[第二天]],
		loginAwardName = [[800金币]],
		loginAwardIcon = [[gold_1]],
		loginAward = {goodsId=1,amount=800},
		recharge = 50,
		rechargeAwardName = [[10000金币]],
		rechargeAwardIcon = [[gold_2]],
		rechargeAward = {goodsId=1,amount=10000},
	},
 {
		id = 3,
		day = [[第三天]],
		loginAwardName = [[1000金币]],
		loginAwardIcon = [[gold_1]],
		loginAward = {goodsId=1,amount=1000},
		recharge = 100,
		rechargeAwardName = [[20000金币]],
		rechargeAwardIcon = [[gold_2]],
		rechargeAward = {goodsId=1,amount=20000},
	},
 {
		id = 4,
		day = [[第四天]],
		loginAwardName = [[1200金币]],
		loginAwardIcon = [[gold_1]],
		loginAward = {goodsId=1,amount=1200},
		recharge = 150,
		rechargeAwardName = [[30000金币]],
		rechargeAwardIcon = [[gold_2]],
		rechargeAward = {goodsId=1,amount=30000},
	},
 {
		id = 5,
		day = [[第五天]],
		loginAwardName = [[1500金币]],
		loginAwardIcon = [[gold_1]],
		loginAward = {goodsId=1,amount=1500},
		recharge = 200,
		rechargeAwardName = [[40000金币]],
		rechargeAwardIcon = [[gold_2]],
		rechargeAward = {goodsId=1,amount=40000},
	},
 {
		id = 6,
		day = [[第六天]],
		loginAwardName = [[2000金币]],
		loginAwardIcon = [[gold_1]],
		loginAward = {goodsId=1,amount=2000},
		recharge = 300,
		rechargeAwardName = [[60000金币]],
		rechargeAwardIcon = [[gold_2]],
		rechargeAward = {goodsId=1,amount=60000},
	},
 {
		id = 7,
		day = [[第七天(登录送炮塔)]],
		loginAwardName = [[极光魅影(3小时)]],
		loginAwardIcon = [[gun_05]],
		loginAward = {gunId=3,time=10800},
		recharge = 500,
		rechargeAwardName = [[极光魅影]],
		rechargeAwardIcon = [[gun_05]],
		rechargeAward = {gunId=3},
	},
}
return login_award_config