--[[
	序号, 权重, 图标, 内容, 奖励类型, 奖励, 跑马灯
	id, weight, icon, content, type, award, notice
]]
local lottery_config = {
	[1] = {
			id = 1,
			weight = 6000,
			icon = [[gold_big]],
			content = [[3万]],
			type = 1,
			award = {goodsId=1,amount=30000},
			notice = 0,
		},
	[2] = {
			id = 2,
			weight = 500,
			icon = [[gun_13]],
			content = [[狂暴修罗(1天)]],
			type = 2,
			award = {gunId=11,time=86400},
			notice = 0,
		},
	[3] = {
			id = 3,
			weight = 5,
			icon = [[gun_13]],
			content = [[狂暴修罗]],
			type = 2,
			award = {gunId=11},
			notice = 1,
		},
	[4] = {
			id = 4,
			weight = 1200,
			icon = [[gun_13]],
			content = [[狂暴修罗(12小时)]],
			type = 2,
			award = {gunId=11,time=43200},
			notice = 0,
		},
	[5] = {
			id = 5,
			weight = 6000,
			icon = [[gold_big]],
			content = [[3万]],
			type = 1,
			award = {goodsId=1,amount=30000},
			notice = 0,
		},
	[6] = {
			id = 6,
			weight = 600,
			icon = [[gold_big]],
			content = [[5万]],
			type = 1,
			award = {goodsId=1,amount=50000},
			notice = 0,
		},
	[7] = {
			id = 7,
			weight = 300,
			icon = [[gold_big]],
			content = [[7万]],
			type = 1,
			award = {goodsId=1,amount=70000},
			notice = 0,
		},
	[8] = {
			id = 8,
			weight = 200,
			icon = [[gold_big]],
			content = [[10万]],
			type = 1,
			award = {goodsId=1,amount=100000},
			notice = 0,
		},
	[9] = {
			id = 9,
			weight = 10,
			icon = [[prize_big_04]],
			content = [[100京东卡]],
			type = 3,
			award = {prizeId=14},
			notice = 1,
		},
	[10] = {
			id = 10,
			weight = 6,
			icon = [[gold_8]],
			content = [[100万]],
			type = 3,
			award = {goodsId=1,amount=1000000},
			notice = 1,
		},
	[11] = {
			id = 11,
			weight = 50,
			icon = [[prize_big_03]],
			content = [[50京东卡]],
			type = 3,
			award = {prizeId=36},
			notice = 1,
		},
	[12] = {
			id = 12,
			weight = 200,
			icon = [[gold_big]],
			content = [[10万]],
			type = 1,
			award = {goodsId=1,amount=100000},
			notice = 0,
		},
	[13] = {
			id = 13,
			weight = 300,
			icon = [[gold_big]],
			content = [[7万]],
			type = 1,
			award = {goodsId=1,amount=70000},
			notice = 0,
		},
	[14] = {
			id = 14,
			weight = 600,
			icon = [[gold_big]],
			content = [[5万]],
			type = 1,
			award = {goodsId=1,amount=50000},
			notice = 0,
		},
}
return lottery_config