--[[
	ID, 类型, 内容, 次数, 时间间隔, 优先级, 开始时间, 结束时间
	id, type, content, times, timeInterval, priority, startTime, endTime
]]
local marquee = {
	[1] = {
			id = 1,
			type = 1,
			content = [[玩家<font color=#fff23a>%s</font>捕获了<font color=#fff23a>%s</font>!]],
			times = 1,
			timeInterval = 0,
			priority = 4,
			startTime = 0,
			endTime = 0,
		},
	[2] = {
			id = 2,
			type = 2,
			content = [[<font size=25 color=#ea00ff outline=#000000,1>玩家</font><font size=25 color=#ffed53 outline=#000000,1>%s</font><font size=25 color=#ea00ff outline=#000000,1>使用</font><font size=25 color=#ffed53 outline=#000000,1>%s张夺宝卡</font><font size=25 color=#ea00ff outline=#000000,1>，兑换了</font><font size=25 color=#ffed53 outline=#000000,1>%s</font><font size=25 color=#ea00ff outline=#000000,1>,激动得热泪盈眶！</font>]],
			times = 1,
			timeInterval = 0,
			priority = 2,
			startTime = 0,
			endTime = 0,
		},
	[3] = {
			id = 3,
			type = 1,
			content = [[玩家<font color=#fff23a>%s</font>找刺激获得<font color=#fff23a>%s张夺宝卡</font>，开心的不要不要的！]],
			times = 1,
			timeInterval = 0,
			priority = 4,
			startTime = 0,
			endTime = 0,
		},
	[4] = {
			id = 4,
			type = 1,
			content = [[玩家<font color=#fff23a>%s</font>开宝箱开出<font color=#fff23a>%s</font>张夺宝卡，开心的不行不行的！]],
			times = 1,
			timeInterval = 0,
			priority = 4,
			startTime = 0,
			endTime = 0,
		},
	[5] = {
			id = 5,
			type = 1,
			content = [[天降祥瑞，河清三日，玩家小手一抖<font color=#fff23a>%s</font>在充值转盘活动抽到<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 4,
			startTime = 0,
			endTime = 0,
		},
	[6] = {
			id = 6,
			type = 2,
			content = [[<font size=25 color=#ea00ff outline=#000000,1>喜从天降，玩家</font><font size=25 color=#ffed53 outline=#000000,1>%s</font><font size=25 color=#ea00ff outline=#000000,1>仅仅使用</font><font size=25 color=#ffed53 outline=#000000,1>%s张夺宝卡</font><font size=25 color=#ea00ff outline=#000000,1>，在夺宝活动中获得</font><font size=25 color=#ffed53 outline=#000000,1>%s</font><font size=25 color=#ea00ff outline=#000000,1>！</font>]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[7] = {
			id = 7,
			type = 1,
			content = [[玩家<font color=#fff23a>%s</font>完成了首次充值，领取了<font color=#fff23a>1张夺宝卡</font>和<font color=#fff23a>30000金币</font>！]],
			times = 1,
			timeInterval = 0,
			priority = 3,
			startTime = 0,
			endTime = 0,
		},
	[8] = {
			id = 8,
			type = 1,
			content = [[玩家<font color=#fff23a>%s</font>力压群雄，在竞技场中拔得头筹，获得了<font color=#fff23a>%s</font>金币!]],
			times = 1,
			timeInterval = 0,
			priority = 3,
			startTime = 0,
			endTime = 0,
		},
	[9] = {
			id = 9,
			type = 1,
			content = [[玩家<font color=#fff23a>%s</font>力压群雄，在竞技场中拔得头筹，获得了<font color=#fff23a>%s</font>夺宝卡!]],
			times = 1,
			timeInterval = 0,
			priority = 3,
			startTime = 0,
			endTime = 0,
		},
	[10] = {
			id = 10,
			type = 2,
			content = [[<font size=25 color=#ea00ff outline=#000000,1>喜大普奔，玩家</font><font size=25 color=#ffed53 outline=#000000,1>%s</font><font size=25 color=#ea00ff outline=#000000,1>鸿运当头，在奖品来袭活动中获得了</font><font size=25 color=#ffed53 outline=#000000,1>%s</font><font size=25 color=#ea00ff outline=#000000,1>！</font>]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[11] = {
			id = 11,
			type = 2,
			content = [[<font color=#fff23a>%s</font>洪福齐天，在充值转盘活动抽到<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[12] = {
			id = 12,
			type = 2,
			content = [[<font color=#fff23a>%s</font>好运连连，在许愿池中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[13] = {
			id = 13,
			type = 2,
			content = [[<font color=#fff23a>%s</font>洪福齐天，在开心刮刮乐中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[14] = {
			id = 14,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在寻宝中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[15] = {
			id = 15,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在疯狂宝箱中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[16] = {
			id = 16,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在幸运祈福中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[17] = {
			id = 17,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在积分抽奖中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[18] = {
			id = 18,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在摇钱树中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[19] = {
			id = 19,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在龙宫宝藏中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[20] = {
			id = 20,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在海底遗迹中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[21] = {
			id = 21,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在砸金蛋中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
	[22] = {
			id = 22,
			type = 2,
			content = [[<font color=#fff23a>%s</font>鸿运当头，在彩金炮抽奖中获得<font color=#fff23a>%s</font>，运气真是好极了！]],
			times = 1,
			timeInterval = 0,
			priority = 1,
			startTime = 0,
			endTime = 0,
		},
}
return marquee