--[[
	类型, 数量, 图标, 内容, 展示, 奖励类型, 奖励, 跑马灯
	id, num, icon, content, display, type, award, notice
]]
local money_tree_config = {
	[1] = {
			id = 1,
			num = 28386,
			icon = [[gold_big]],
			content = [[1万]],
			display = 0,
			type = 1,
			award = {goodsId=1,amount=10000},
			notice = 0,
		},
	[2] = {
			id = 2,
			num = 4258,
			icon = [[gold_big]],
			content = [[2万]],
			display = 0,
			type = 1,
			award = {goodsId=1,amount=20000},
			notice = 0,
		},
	[3] = {
			id = 3,
			num = 2365,
			icon = [[gold_big]],
			content = [[3万]],
			display = 0,
			type = 1,
			award = {goodsId=1,amount=30000},
			notice = 0,
		},
	[4] = {
			id = 4,
			num = 804,
			icon = [[gold_big]],
			content = [[5万]],
			display = 0,
			type = 1,
			award = {goodsId=1,amount=50000},
			notice = 0,
		},
	[5] = {
			id = 5,
			num = 397,
			icon = [[gold_big]],
			content = [[10万]],
			display = 0,
			type = 1,
			award = {goodsId=1,amount=100000},
			notice = 0,
		},
	[6] = {
			id = 6,
			num = 161,
			icon = [[gold_big]],
			content = [[20万]],
			display = 0,
			type = 1,
			award = {goodsId=1,amount=200000},
			notice = 0,
		},
	[7] = {
			id = 7,
			num = 95,
			icon = [[gold_big]],
			content = [[50万]],
			display = 5,
			type = 1,
			award = {goodsId=1,amount=500000},
			notice = 1,
		},
	[8] = {
			id = 8,
			num = 800,
			icon = [[prize_big_03]],
			content = [[50京东卡]],
			display = 4,
			type = 3,
			award = {prizeId=13},
			notice = 1,
		},
	[9] = {
			id = 9,
			num = 80,
			icon = [[prize_big_04]],
			content = [[100京东卡]],
			display = 3,
			type = 3,
			award = {prizeId=14},
			notice = 1,
		},
	[10] = {
			id = 10,
			num = 47,
			icon = [[prize_big_05]],
			content = [[300京东卡]],
			display = 2,
			type = 3,
			award = {prizeId=15},
			notice = 1,
		},
	[11] = {
			id = 11,
			num = 13247,
			icon = [[gun_12]],
			content = [[炮塔(1天)]],
			display = 0,
			type = 2,
			award = {gunId=10,time=86400},
			notice = 0,
		},
	[12] = {
			id = 12,
			num = 18,
			icon = [[gun_12]],
			content = [[炮塔]],
			display = 1,
			type = 2,
			award = {gunId=10},
			notice = 1,
		},
}
return money_tree_config