--[[
	类型, 权重, 图标, 内容, 奖励类型, 奖励, 跑马灯
	id, weight, icon, content, type, award, notice
]]
local score_lottery_config = {
	[1] = {
			id = 1,
			weight = 1000,
			icon = [[card_2]],
			content = [[夺宝卡X2]],
			type = 1,
			award = {goodsId=2,amount=2},
			notice = 0,
		},
	[2] = {
			id = 2,
			weight = 5000,
			icon = [[gold_big]],
			content = [[5000金币]],
			type = 1,
			award = {goodsId=1,amount=5000},
			notice = 0,
		},
	[3] = {
			id = 3,
			weight = 5,
			icon = [[gun_10]],
			content = [[炮塔]],
			type = 2,
			award = {gunId=8},
			notice = 1,
		},
	[4] = {
			id = 4,
			weight = 2500,
			icon = [[gold_big]],
			content = [[8000金币]],
			type = 1,
			award = {goodsId=1,amount=8000},
			notice = 0,
		},
	[5] = {
			id = 5,
			weight = 800,
			icon = [[card_3]],
			content = [[夺宝卡X3]],
			type = 1,
			award = {goodsId=2,amount=3},
			notice = 0,
		},
	[6] = {
			id = 6,
			weight = 300,
			icon = [[gold_big]],
			content = [[20000金币]],
			type = 1,
			award = {goodsId=1,amount=20000},
			notice = 0,
		},
	[7] = {
			id = 7,
			weight = 100,
			icon = [[gold_big]],
			content = [[50000金币]],
			type = 1,
			award = {goodsId=1,amount=50000},
			notice = 0,
		},
	[8] = {
			id = 8,
			weight = 500,
			icon = [[card_3]],
			content = [[夺宝卡X5]],
			type = 1,
			award = {goodsId=2,amount=5},
			notice = 0,
		},
	[9] = {
			id = 9,
			weight = 2500,
			icon = [[gold_big]],
			content = [[8000金币]],
			type = 1,
			award = {goodsId=1,amount=8000},
			notice = 0,
		},
	[10] = {
			id = 10,
			weight = 20,
			icon = [[gold_8]],
			content = [[25万金币]],
			type = 1,
			award = {goodsId=1,amount=250000},
			notice = 1,
		},
	[11] = {
			id = 11,
			weight = 5000,
			icon = [[gold_big]],
			content = [[5000金币]],
			type = 1,
			award = {goodsId=1,amount=5000},
			notice = 0,
		},
	[12] = {
			id = 12,
			weight = 300,
			icon = [[card_3]],
			content = [[夺宝卡X10]],
			type = 1,
			award = {goodsId=2,amount=10},
			notice = 0,
		},
	[13] = {
			id = 13,
			weight = 100,
			icon = [[gold_big]],
			content = [[50000金币]],
			type = 1,
			award = {goodsId=1,amount=50000},
			notice = 0,
		},
	[14] = {
			id = 14,
			weight = 300,
			icon = [[gold_big]],
			content = [[20000金币]],
			type = 1,
			award = {goodsId=1,amount=20000},
			notice = 0,
		},
}
return score_lottery_config